StartupEvents.registry('block', event => { 
    event.create('zti:1compressed_cobblestone').displayName('压缩圆石t1')
    .mapColor(0x5a5a5a)
    .hardness(1.5)
    .resistance(10)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create('zti:2compressed_cobblestone').displayName('压缩圆石t2')
    .mapColor(0x2d2d2d)
    .hardness(1.5)
    .resistance(10)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create('zti:3compressed_cobblestone').displayName('压缩圆石t3')
    .mapColor(0x161616)
    .hardness(1.5)
    .resistance(10)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create('zti:star_coagulator').displayName('星之凝聚器')
    .lightLevel(1)
    .mapColor(0x649090)
    .hardness(1.5)
    .resistance(10)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')

    event.create('zti:furnace_casing').displayName('熔炼机械方块')
    .mapColor(0x5a5a5a)
    .hardness(1.5)
    .resistance(10)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_wooden_tool')
})